[build]
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/functions/:splat"
    status = 200

# Form return
[[redirects]]
    from = "/thanks/pt"
    to = "/thanks-pt.html"
    status = 200

[[redirects]]
    from = "/thanks/es"
    to = "/thanks-es.html"
    status = 200

[[redirects]]
    from = "/thanks/fr"
    to = "/thanks-fr.html"
    status = 200

[[redirects]]
    from = "/thanks/*"
    to = "/thanks-en.html"
    status = 200    

# Privacy Policy
[[redirects]]
    from = "/privacy/pt"
    to = "/pages/privacy-pt.html"
    status = 200

[[redirects]]
    from = "/privacy/es"
    to = "/pages/privacy-es.html"
    status = 200

[[redirects]]
    from = "/privacy/en"
    to = "/pages/privacy-en.html"
    status = 200    

[[redirects]]
    from = "/privacy/fr"
    to = "/pages/privacy-fr.html"
    status = 200        

[[redirects]]
    from = "/privacy"
    to = "/pages/privacy-pt.html"
    status = 200
    conditions = {Language = ["pt"]}
    force = true

[[redirects]]
    from = "/privacy"
    to = "/pages/privacy-es.html"
    status = 200
    conditions = {Language = ["es"]}
    force = true

[[redirects]]
    from = "/privacy"
    to = "/pages/privacy-fr.html"
    status = 200
    conditions = {Language = ["fr"]}      
    force = true  

[[redirects]]
    from = "/privacy"
    to = "/pages/privacy-en.html"
    status = 200
    force = true

# EULA
[[redirects]]
    from = "/eula/pt"
    to = "/pages/eula-pt.html"
    status = 200

[[redirects]]
    from = "/eula/es"
    to = "/pages/eula-es.html"
    status = 200

[[redirects]]
    from = "/eula/en"
    to = "/pages/eula-en.html"
    status = 200    

[[redirects]]
    from = "/eula/fr"
    to = "/pages/eula-fr.html"
    status = 200        

[[redirects]]
    from = "/eula"
    to = "/pages/eula-pt.html"
    status = 200
    conditions = {Language = ["pt"]}
    force = true

[[redirects]]
    from = "/eula"
    to = "/pages/eula-es.html"
    status = 200
    conditions = {Language = ["es"]}
    force = true

[[redirects]]
    from = "/eula"
    to = "/pages/eula-fr.html"
    status = 200
    conditions = {Language = ["fr"]}      
    force = true  

[[redirects]]
    from = "/eula"
    to = "/pages/eula-en.html"
    status = 200
    force = true


# HELP
[[redirects]]
    from = "/help/pt"
    to = "/pages/help-pt.html"
    status = 200

[[redirects]]
    from = "/help/es"
    to = "/pages/help-es.html"
    status = 200

[[redirects]]
    from = "/help/en"
    to = "/pages/help-en.html"
    status = 200    

[[redirects]]
    from = "/help/fr"
    to = "/pages/help-fr.html"
    status = 200   
    

[[redirects]]
    from = "/help"
    to = "/pages/help-pt.html"
    status = 200
    conditions = {Language = ["pt"]}      
    force = true  
    
[[redirects]]
    from = "/help"
    to = "/pages/help-es.html"
    status = 200
    conditions = {Language = ["es"]}    
    force = true  
    
[[redirects]]
    from = "/help"
    to = "/pages/help-fr.html"
    status = 200
    conditions = {Language = ["fr"]}    
    force = true  

[[redirects]]
    from = "/help"
    to = "/pages/help-en.html"
    status = 200
    conditions = {Language = ["en"]}    


# 404 Errors
[[redirects]]
    from = "/*"
    to = "/404-pt.html"
    status = 404
    conditions = {Language = ["pt"]}      
    
[[redirects]]
    from = "/*"
    to = "/404-es.html"
    status = 404
    conditions = {Language = ["es"]}    
    
[[redirects]]
    from = "/*"
    to = "/404-fr.html"
    status = 404
    conditions = {Language = ["fr"]}    

[[redirects]]
    from = "/*"
    to = "/404-en.html"
    status = 404
    conditions = {Language = ["en"]}    
